# Generated by Django 4.1.1 on 2022-09-10 18:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PersonalTraits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Id",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="",
                        help_text="აირჩიეთ სურათი",
                        upload_to="images",
                        verbose_name=" სურათი",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="გამოიყენეთ მხოლოდ ასოები",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-zA-Z ]*$",
                                message="გამოიყენეთ მხოლოდ ლათინური ასოები",
                            )
                        ],
                        verbose_name=" სახელი",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="გამოიყენეთ მხოლოდ ასოები",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-zA-Z ]*$",
                                message="გამოიყენეთ მხოლოდ ლათინური ასოები",
                            )
                        ],
                        verbose_name=" გვარი",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Tbilisi", "თბილისი"),
                            ("Batumi", "ბათუმი"),
                            ("Kutaisi", "ქუთაისი"),
                            ("Zestafoni", "ზესტაფონი"),
                        ],
                        help_text="აირჩიეთ ქალაქი",
                        max_length=100,
                        verbose_name=" ქალაქი",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("კაცი", "კაცი"),
                            ("ქალი", "ქალი"),
                            ("არ მინდა დასახელება", "არ მინდა დასახელება"),
                        ],
                        help_text="აირჩიეთ სქესი",
                        max_length=20,
                        verbose_name=" სქესი",
                    ),
                ),
                (
                    "citizen",
                    models.CharField(
                        choices=[
                            ("საქართველო", "საქართველო"),
                            ("უცხო ქვეყნის მოქალაქე", "უცხო ქვეყნის მოქალაქე"),
                        ],
                        help_text="ამოირჩიეთ ქალაქი",
                        max_length=50,
                        verbose_name=" მოქალაქეობა",
                    ),
                ),
                (
                    "card_num",
                    models.CharField(
                        help_text="გამოიყენეთ მხოლოდ ასოები და ციფრები",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator("^[a-zA-Z0-9_]*$")
                        ],
                        verbose_name=" ბარათის ნომერი",
                    ),
                ),
                (
                    "number_id",
                    models.CharField(
                        help_text="გამოიყენეთ მხოლოდ ციფრები",
                        max_length=11,
                        validators=[django.core.validators.RegexValidator("^[0-9]*$")],
                        verbose_name=" პირადობის ნომერი",
                    ),
                ),
                ("date_of_birth", models.DateField(verbose_name=" დაბადების თარიღი")),
                ("validit_period", models.DateField(verbose_name=" გაუქმების თარიღი")),
                ("check_in", models.TimeField(null=True)),
                (
                    "dep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dep",
                        to="id.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Arival_time",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name=" სახელი"
                    ),
                ),
                ("comment", models.TextField(blank=True, max_length=500, null=True)),
                ("check_out", models.TimeField(null=True)),
                (
                    "person_number",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="id.id",
                    ),
                ),
            ],
        ),
    ]
