# Generated by Django 4.1.1 on 2022-09-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("id", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="id",
            name="persn",
        ),
        migrations.AddField(
            model_name="id",
            name="person",
            field=models.ManyToManyField(related_name="pers", to="id.personaltraits"),
        ),
    ]
