# Generated by Django 4.1.1 on 2022-09-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("id", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="id",
            name="check_in",
        ),
        migrations.AddField(
            model_name="arival_time",
            name="check_in",
            field=models.TimeField(null=True),
        ),
    ]
