# Generated by Django 4.1.1 on 2022-09-10 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("id", "0002_remove_id_check_in_arival_time_check_in"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department_child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dep_child",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="id.department",
                    ),
                ),
            ],
        ),
    ]
