# Generated by Django 4.1.1 on 2022-09-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("id", "0002_id_person_alter_personaltraits_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="id",
            name="person",
        ),
        migrations.AlterField(
            model_name="personaltraits",
            name="person",
            field=models.CharField(max_length=30),
        ),
    ]
