# Generated by Django 4.1.1 on 2022-09-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("id", "0003_remove_id_person_alter_personaltraits_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="id",
            name="citizen",
            field=models.CharField(
                choices=[
                    ("Georgia", "საქართველო"),
                    ("Foreign country", "უცხო ქვეყნის მოქალაქე"),
                ],
                help_text="ამოირჩიეთ ქალაქი",
                max_length=50,
                verbose_name=" მოქალაქეობა",
            ),
        ),
        migrations.AlterField(
            model_name="id",
            name="sex",
            field=models.CharField(
                choices=[
                    ("Men", "კაცი"),
                    ("Women", "ქალი"),
                    ("Dont wanna say", "არ მინდა დასახელება"),
                ],
                help_text="აირჩიეთ სქესი",
                max_length=20,
                verbose_name=" სქესი",
            ),
        ),
    ]
