# Generated by Django 4.1.1 on 2022-09-10 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("id", "0003_department_child"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Department_child",
        ),
    ]
