# Generated by Django 4.1.1 on 2022-09-14 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("id", "0004_alter_id_citizen_alter_id_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arival_time",
            name="person_number",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="id.id"
            ),
        ),
    ]
