# Generated by Django 4.1.1 on 2022-09-11 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("id", "0005_department_parent_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="id",
            name="person",
            field=models.ManyToManyField(related_name="pers", to="id.personaltraits"),
        ),
        migrations.AlterField(
            model_name="department",
            name="parent_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="id.department",
                verbose_name=" უფროსი",
            ),
        ),
    ]
