# Generated by Django 4.1.1 on 2022-09-14 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("id", "0005_alter_arival_time_person_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arival_time",
            name="person_number",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ids",
                to="id.id",
            ),
        ),
    ]
